CHANGELOG.md
packages/narrat/examples/games/default/data/audio.yaml
packages/narrat/examples/games/default/data/config.yaml
packages/narrat/examples/games/default/data/items.yaml
packages/narrat/examples/games/default/data/quests.yaml
packages/narrat/examples/games/default/data/screens.yaml
packages/narrat/examples/games/default/data/skills.yaml
packages/narrat/package.json
packages/narrat/src/config.ts
packages/narrat/src/main.ts
packages/narrat/src/utils/ajax.ts

feat: split config files

---

CHANGELOG.md
packages/narrat/.vscode/settings.json
packages/narrat/examples/games/default/data/config.yaml
packages/narrat/examples/games/demo/data/config.yaml
packages/narrat/examples/games/empty/data/config.yaml
packages/narrat/examples/games/rpg/data/config.yaml
packages/narrat/src/app.vue
packages/narrat/src/components/MainMenu.vue
packages/narrat/src/components/dialog-picture.vue
packages/narrat/src/components/game-dialog.vue
packages/narrat/src/components/menu-buttons.vue
packages/narrat/src/components/screens.vue
packages/narrat/src/config.ts
packages/narrat/src/defaultConfig.ts
packages/narrat/src/main.ts
packages/narrat/src/stores/rendering-store.ts

feat: mobile device layout

---

CHANGELOG.md
packages/narrat/examples/games/default/data/audio.yaml
packages/narrat/examples/games/default/scripts/default.nar
packages/narrat/package.json
packages/narrat/src/stores/skills.ts
packages/narrat/src/vm/commands/choice.ts
packages/narrat/src/vm/commands/index.ts
packages/narrat/src/vm/commands/skill-commands.ts
packages/narrat/src/vm/vm-helpers.ts

feat: repeatable skill rolls

---

packages/create-narrat/template/package.json
packages/narrat/examples/games/default/scripts/default.nar

update create-narrat for 10.0

---

CHANGELOG.md
docs/.vitepress/config.js
docs/others/scripting-limitations.md
docs/scripting/plugins.md
packages/narrat/examples/games/default/scripts/default.nar
packages/narrat/package.json
packages/narrat/src/stores/screen-objects-store.ts
packages/narrat/src/stores/vm-store.ts
packages/narrat/src/utils/data-helpers.ts

fix: sprites nesting issue

---

CHANGELOG.md
packages/narrat/examples/games/default/scripts/default.nar
packages/narrat/package.json
packages/narrat/src/components/screen-objects/screen-object.vue
packages/narrat/src/css/main.css

tooltips working

---

CHANGELOG.md
docs/.vitepress/config.js
docs/commands/all-commands.md
docs/commands/stats/index.md
docs/guides/getting-started.md
packages/narrat/examples/games/default/scripts/default.nar
packages/narrat/package.json
packages/narrat/src/utils/data-helpers.ts
packages/narrat/src/vm/commands/index.ts
packages/narrat/src/vm/commands/skill-commands.ts

Get skill check

---

CHANGELOG.md
packages/narrat/examples/games/default/scripts/default.nar
packages/narrat/package.json
packages/narrat/src/stores/hud-stats-store.ts
packages/narrat/src/stores/inventory-store.ts
packages/narrat/src/stores/main-store.ts
packages/narrat/src/stores/quest-log.ts
packages/narrat/src/stores/screen-objects-store.ts
packages/narrat/src/stores/screens-store.ts
packages/narrat/src/stores/skills.ts

fix: save data issues

---

docs/commands/if-function.md
packages/narrat/examples/games/default/scripts/default.nar
packages/narrat/src/vm/commands/if.ts
packages/narrat/src/vm/vm-helpers.ts
packages/narrat/src/vm/vm-parser.ts
pnpm-lock.yaml

feat(conditions): new elseif conditions feature

---

packages/narrat/examples/games/default/scripts/default.nar
packages/narrat/src/vm/commands/choice.ts

feat(choices): choices with both skill checks and ifs working

---

packages/narrat/examples/games/default/data/config.yaml
packages/narrat/src/components/MainMenu.vue
packages/narrat/src/components/game-dialog.vue
packages/narrat/src/components/inventory/item-details.vue
packages/narrat/src/components/menu-buttons.vue
packages/narrat/src/components/settings/setting-widget.vue
packages/narrat/src/components/settings/settings-menu.vue
packages/narrat/src/config.ts
packages/narrat/src/config/config-input.ts
packages/narrat/src/config/config-output.ts
packages/narrat/src/config/layout-config.ts
packages/narrat/src/config/settings-config.ts
packages/narrat/src/css/main.css
packages/narrat/src/main.ts
packages/narrat/src/stores/audio-store.ts
packages/narrat/src/stores/main-store.ts
packages/narrat/src/stores/settings-store.ts
packages/narrat/src/types/game-save.ts
packages/narrat/src/utils/save-helpers.ts
packages/narrat/src/utils/skillchecks.test.ts
packages/narrat/vite.config.ts

See [forum post](https://narrat.discourse.group/t/custom-settings-feature/34)

feat(settings): new settings and custom settings feature

---

packages/narrat/src/components/MainMenu.vue
packages/narrat/src/components/settings/setting-widget.vue
packages/narrat/src/components/settings/settings-menu.vue

Just a small syntax cvonversion

chore(refactor): convert components to composition API

---

docs/.vitepress/config.js
docs/features/game-settings.md
packages/narrat/examples/games/default/data/config.yaml
packages/narrat/examples/games/default/scripts/default.narrat
packages/narrat/src/exports/plugins.ts
packages/narrat/src/stores/main-store.ts
packages/narrat/src/stores/settings-store.ts
packages/narrat/src/utils/data-helpers.ts
packages/narrat/src/utils/save-helpers.ts
packages/narrat/src/vm/commands/index.ts
packages/narrat/src/vm/commands/settings-commands.ts
packages/narrat/src/vm/vm.ts

Finished all the last bits of the custom settings feature + added some demo code and documented it

feat(settings): finished new game settings feature + related docs

---

docs/.vitepress/config.js
package.json
packages/narrat/package.json
pnpm-lock.yaml

also added some links to the docs

chore(updates): update vite, vitest, vitepress, windicss

---

docs/.vitepress/config.js
docs/guides/customising-ui.md
docs/guides/using-custom-fonts.md
docs/index.md

Update to docs with custom fonts instructions

docs(CSS): Fonts customisation guide

---

docs/scripting/language-syntax.md

docs: arrays and objects documented in language syntax guide

---

docs/.vitepress/config.js
docs/commands/all-commands.md
docs/commands/left-side-viewport-commands/set-screen.md
docs/features/dynamic-sprites-text-objects.md
docs/features/viewport.md
docs/index.md
packages/narrat/src/components/saves/save-slot-ui.vue
packages/narrat/src/components/screen-layer.vue
packages/narrat/src/config.ts
packages/narrat/src/constants.ts
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/stores/screen-objects-store.ts

(see new docs)
**BEFORE**:
**AFTER**:

feat(Screens): Add a way to easily create empty screens

---

docs/.vitepress/config.js
docs/commands/all-commands.md
docs/features/changing-player-character.md
packages/narrat/examples/games/default/data/characters.yaml
packages/narrat/src/config/characters-config.ts
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/stores/config-store.ts
packages/narrat/src/stores/main-store.ts
packages/narrat/src/stores/vm-store.ts
packages/narrat/src/vm/commands/choice.ts
packages/narrat/src/vm/commands/index.ts
packages/narrat/src/vm/commands/text-field.ts
packages/narrat/src/vm/commands/text.ts
packages/narrat/src/vm/commands/util-commands.ts
packages/narrat/src/vm/vm-helpers.ts

See documentation added in this PR for info

feat(characters): Ability to change the player character during the game

---

docs/commands/choice-function.md

old code syntax in the example

docs: Update choice-function.md

---

packages/narrat/examples/games/default/data/screens.yaml
packages/narrat/src/components/StartMenu.vue
packages/narrat/src/components/debug/debug-jumping.vue
packages/narrat/src/components/debug/debug-menu.vue
packages/narrat/src/components/game-dialog.vue
packages/narrat/src/components/game-splash/game-splash.vue
packages/narrat/src/components/in-game.vue
packages/narrat/src/components/screen-layer.vue
packages/narrat/src/components/screen-objects/screen-object.vue
packages/narrat/src/components/screens.vue
packages/narrat/src/components/screens/screen-types.ts
packages/narrat/src/components/start-menu/start-menu-button.vue
packages/narrat/src/components/start-menu/start-menu-types.ts
packages/narrat/src/components/utils/yes-no.vue
packages/narrat/src/css/main.css
packages/narrat/src/dialog-box.vue
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/inputs/useNavigation.ts
packages/narrat/src/stores/inputs-store.ts
packages/narrat/src/stores/main-store.ts
packages/narrat/src/stores/screen-objects-store.ts
packages/narrat/src/stores/screens-store.ts
packages/narrat/src/utils/math-utils.ts
packages/narrat/src/utils/viewport-utils.ts

Lots of refactor and changes to make the new input system work in more places, including being able to cycle through buttons/sprites to interact with them

feat: New gamepad/keyboard input system working in more places and full viewport support

---

packages/narrat/examples/games/default/data/config.yaml
packages/narrat/examples/games/default/data/screens.yaml
packages/narrat/src/components/StartMenu.vue
packages/narrat/src/components/game-dialog.vue
packages/narrat/src/components/in-game.vue
packages/narrat/src/components/screen-layer.vue
packages/narrat/src/components/screen-objects/screen-object.vue
packages/narrat/src/components/screens.vue
packages/narrat/src/components/screens/viewport-button.vue
packages/narrat/src/config.ts
packages/narrat/src/config/common-config.ts
packages/narrat/src/dialog-box.vue
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/inputs/useNavigation.ts
packages/narrat/src/stores/inputs-store.ts
packages/narrat/src/stores/screens-store.ts
packages/narrat/src/utils/math-utils.ts

The previous PR was merged with a commit missing...

feat: new inputs system working in most places

---

docs/commands/all-commands.md
packages/narrat/src/examples/default/scripts.ts
packages/narrat/src/examples/default/scripts/arrays.narrat
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/vm/commands/array-commands.ts
packages/narrat/src/vm/commands/index.ts
packages/narrat/src/vm/commands/object-commands.ts

feat: new array functions

---

packages/narrat/src/examples/default/scripts.ts
packages/narrat/src/examples/default/scripts/arrays.narrat
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/examples/default/scripts/objects.narrat

Added test script to verify new array functions work

chore: tested new array functions

---

docs/features/viewport.md
packages/narrat/examples/games/default/data/screens.yaml
packages/narrat/src/components/screen-layer.vue
packages/narrat/src/config/screens-config.ts
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/utils/images-loader.ts

See the added docs for details

feat: new feature for video backgrounds in screens

---

packages/narrat/src/components/quests/QuestDetails.vue
packages/narrat/src/config.ts
packages/narrat/src/config/quests-config.ts
packages/narrat/src/stores/quest-log.ts
packages/narrat/src/vm/commands/index.ts
packages/narrat/src/vm/commands/quest-commands.ts

feat: new feature for configurable quest endings

---

demo-template/public/data/demo.narrat
docs/examples/example-narrat-script.md
packages/narrat-editor/src/narrat/scripts/game.narrat
packages/narrat/src/examples/demo/scripts/demo.narrat

- [n/a] Linked an issue for this PR (or no issue is relevant)
I noticed a a link was broken when trying the demo, so I came to fix it.
Just changed the hyperlink to point at what I think are the correct places in your repositories.
No breaks, only fixes.

Correct hyperlink that ended in a github 404 in 4 places.

---

docs/features/save-and-load.md
packages/narrat/src/components/StartMenu.vue
packages/narrat/src/config/common-config.ts
packages/narrat/src/examples/default/config/common.yaml

feat: feature to disable saves

---

packages/desktop-editor/package.json
packages/desktop-editor/src-tauri/Cargo.lock
packages/desktop-editor/src-tauri/Cargo.toml
packages/desktop-editor/src-tauri/src/main.rs
packages/desktop-editor/src-tauri/src/menu.rs
packages/desktop-editor/src-tauri/tauri.conf.json
packages/desktop-editor/src/App.vue
packages/desktop-editor/src/components/editor/EditorPanel.vue
packages/desktop-editor/src/components/preview/PreviewGame.vue
packages/desktop-editor/src/events/tauri-events.ts
packages/desktop-editor/src/filesystem/file-utils.ts
packages/desktop-editor/src/game-runner/narrat-runner.ts
packages/desktop-editor/src/main.ts
packages/desktop-editor/src/pages/HomePage.vue
packages/desktop-editor/src/pages/LoadingPage.vue
packages/desktop-editor/src/preferences/preference-types.ts
packages/desktop-editor/src/stores/application-store.ts
packages/desktop-editor/src/stores/ide-store.ts
packages/desktop-editor/src/stores/preferences-store.ts

The IDE now saves recent projects and can reload them easily

feat: windows compatibility, more IDE features, user preferences working

---

.github/workflows/ide.yml

fix: add pnpm install to IDE publish script

---

docs/.vitepress/config.js
docs/config/achievements-config.md
docs/config/all-config-files.md
docs/config/animations-config.md
docs/config/audio-config.md
docs/config/common-config.md
packages/narrat/src/application/application-start.ts
packages/narrat/src/config.ts
packages/narrat/src/config/config-input.ts
packages/narrat/src/config/config-output.ts
packages/narrat/src/config/preload-config.ts
packages/narrat/src/examples/default/config/index.ts
packages/narrat/src/examples/default/config/preload.yaml
packages/narrat/src/examples/default/config/screens.yaml
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/utils/images-loader.ts
packages/narrat/src/utils/video-loader.ts

Video preloading + more config docs

feat(videos): preload videos + more docs

---

docs/scripting/language-syntax.md
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/vm/parser.test.narrat
packages/narrat/src/vm/simple-script.test.narrat
packages/narrat/src/vm/vm-parser.test.ts
packages/narrat/src/vm/vm-parser.ts

Allows splitting code lines and strings across multiple lines

feat(scripting): multiline scripting feature

---

packages/narrat/src/components/debug/debug-menu.vue
packages/narrat/src/dialog-box.vue
packages/narrat/src/examples/default/scripts/conditions.narrat
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/examples/default/scripts/scripts.ts
packages/narrat/src/stores/inputs-store.ts
packages/narrat/src/vm/commands/if.ts
packages/narrat/src/vm/vm-parser.ts
packages/narrat/src/vm/vm.ts

also fixed using "J" in text fields while in debug mode

fix: elseifs now work with single variables in conditions

---

.github/workflows/main.yml
docs/.vitepress/config-en.ts
docs/features/hotkeys.md
packages/narrat/src/config/common-config.ts
packages/narrat/src/inputs/Inputs.ts

Added configurable hotkeys and doc page

feat(input): Added configurable hotkeys

---

docs/.vitepress/config-en.ts
docs/.vitepress/config-fr.ts
docs/fr/guides/config-files.md
docs/fr/guides/custom-start-buttons.md
docs/fr/guides/customising-ui.md
docs/fr/guides/editing-game.md
docs/fr/guides/getting-help.md
docs/fr/guides/installing-narrat-in-a-web-app.md
docs/fr/guides/themes.md
docs/guides/config-files.md
docs/guides/custom-start-buttons.md
docs/guides/customising-ui.md
docs/guides/editing-game.md
docs/guides/getting-help.md
docs/guides/themes.md
pnpm-lock.yaml

Missing french translations, 
Added a first batch of french translations + sidebar items + search modal translation.
Many links point to an english file because the french file isn't created yet, will do a pass over all links to update them when everything is done.
> ⚠️ NOTE: can't change some properties in the search modal, like `buttonText` and  ``buttonAriaLabel`, don't know how to fix

Typos, formatting, french translations

---

docs/features/dialog-panel.md
packages/narrat/src/config/common-config.ts
packages/narrat/src/dialog-box.vue
packages/narrat/src/examples/default/config/skillchecks.yaml
packages/narrat/src/examples/default/scripts/default.narrat
packages/narrat/src/vm/commands/choice.ts

added showChoicesOutcomes, lockSeenChoices and allowSpacebarInChoices options, new defauly spacebar behaviour on choices

Feat: added config options for choices

---

README.md
packages/narrat/src/dialog-box.vue
packages/narrat/src/stores/audio-store.ts

audio settings only worked when using the master slider, they now correctly update
corrected text field submit localisaiton string to no longer incorrectly capitalise 'field', localised text now displays correctly

fix: Changing audio settings now correctly updates volume
